### ISSUE TITLE
UnresolvedTrack artist returning non-array value

### ISSUE THREAD

**Issue by ZenShibata** [tuneorg/spotify#1]
![image](https://user-images.githubusercontent.com/45705890/149267976-c08e5fe5-3a0a-419f-8f07-64774087b070.png)
![image](https://user-images.githubusercontent.com/45705890/149267983-a522790e-465b-495b-8ad0-869f50fa7a63.png)

**Comment by hydrox19** [comment]
fixed in https://github.com/tuneorg/spotify/commit/6f685f1113cc2df8622346559a5127ef1cb384e0
